### ISSUE TITLE
Only the Privacy Policy section from NY Times website is sent as full article if choosing the "Link with Full Articles" option

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/email-tabs#185] opened 2018-10-16 14:59 UTC
**[Affected versions]:**
- Firefox 62.0.3 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Email Tabs" add-on (0.1.6920) custom built.
- You are logged in to Gmail.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.nytimes.com/ website and wait for the privacy policy to be displayed.
2. Click the "Email-Tabs" toolbar button.
3. Click the "Email Tabs" button.
4. Select the "Link with Full Articles" option and observe the mail's content.

**[Expected result]:**
- The link and the full article of the website are displayed.

**[Actual result]:**
- The source and the privacy policy section are displayed.

**[Notes]:**
- This issue is also reproducible on https://www.nbcnews.com/ and https://screenrant.com/
- This issue is not reproducible after the privacy policy section is dismissed.
- This issue is not reproducible on https://www.foxnews.com/, https://www.nfl.com/ even if the privacy policy is displayed.
- Attached is a screen recording of the issue: 
![cookies](https://user-images.githubusercontent.com/40061643/47025940-193f0100-d16d-11e8-9f11-b6a458b53438.gif)

**Comment by ianb** [comment] 2018-10-18 18:14
We think this will be fixed by #187, closing as a duplicate of that one.

**Comment by Softvision-RemusDranca** [comment] 2018-10-31 16:33
I have verified this issue using the latest version of the "Email Tabs" add-on (0.1.7280) custom built and the issue is still reproducible on https://screenrant.com/ website. 
On https://www.nytimes.com/ page the behavior was changed and now a small content is sent followed by the Privacy Policy.
However, on https://www.nbcnews.com/ the page is sent as a screenshot, as expected in fix #193.
Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.

Considering this I will reopen this issue.

**Comment by ianb** [comment] 2018-11-01 18:15
I think this is acceptable, screenrant.com is quirky, but not terrible:

![image](https://user-images.githubusercontent.com/44390/47870672-1a606700-ddd8-11e8-92d7-7299d21143b2.png)

At worst, users can select the link+screenshot template if they want to send a page and it renders weird in the email.

**Closed by ianb** 2018-11-01 18:15 UTC
Labels: [QA]:Major issue
